### ISSUE TITLE
0.5.1 bump to 0.5.2 is break or not?

### ISSUE THREAD

**Issue by driftluo** [brson/home#21]
0.5.1 can build on rustc 1.38
0.5.2 can not build on rustc 1.38, it must use rust 1.39+

Because rustc 1.39 allow match [bind-by-move](https://github.com/rust-lang/rust/blob/master/RELEASES.md#language-1) and `home` use it:
https://github.com/brson/home/blob/fd7d4257823ae58e72803ac34443e6ee145ad7f1/src/lib.rs#L113

**Comment by tesuji** [comment]
Let's me consider the reverse dependencies of home: If the main majority is on lower 
Rust version, I would yank 0.5.2 version and publish 0.5.3 that doesn't depend on newer
Rust features.

**Comment by tesuji** [comment]
The important crate like [rustsec][1] and [cargo-audit][2] use Rust 1.36.
I think I will publish new version soon.

[1]: https://github.com/RustSec/rustsec-crate/blob/8b2fb1c4cd71e94c8d7d6cdfedc233e418f373a0/.github/workflows/rust.yml#L59
[2]: https://github.com/RustSec/cargo-audit/blob/9d99a901cf8db38a087a360b4c828102b08abb9b/.github/workflows/rust.yml#L38

**Comment by driftluo** [comment]
Yes, I just found out that I couldn't install it using cargo-audit in ci. Fortunately, there is `cargo install xx --locked`, so ci will be fine.

My doubt is whether this is a break or not. The api does not change, but the specific compiler version does not compile.

**Comment by tesuji** [comment]
Closed in 0.5.3: https://crates.io/crates/home
